
# Testing Rmd

this is a test of Rmd inside a Quarto book



https://cran.r-project.org/web/packages/tidytext/tidytext.pdf



```{r}
library(tidyverse)
library(tidytext)
library(gutenbergr)
```


look for a book by title name

```{r}
gutenberg_metadata %>% 
  filter(title == "The Iliad")
```


find works by author

```{r}
gutenberg_works(author == "Carroll, Lewis")

# or use 

gutenberg_works(str_detect(author, "Carroll"))
```


download a book by id

```{r}
book_link = "https://www.gutenberg.org/cache/epub/174/pg174.txt"

book_file = read_file( book_link )

book_df = tibble( book_file )

book_tokens = book_df %>% 
  unnest_tokens(input = book_file, output = word)

book_clean = book_tokens %>% 
  anti_join(stop_words, by='word')


```







```{r}
book_clean %>% 
  filter(word != c("gutenberg","project")) %>% 
  count(word, sort = T)
```

find the words in context

```{r}
library(quanteda)

book_tokens_q = tokens(book_file)

kwic_word = "love"

kwic(book_tokens_q, pattern= kwic_word )
```




```{r}
bing = get_sentiments("bing")

book_clean %>% 
  filter(word != c("gutenberg","project")) %>% 
  inner_join(bing, by= 'word') %>% 
  count( sentiment, sort = T)
```

















